[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "19"
  
[build]
  publish = "dist"
  command = "pnpm run build"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [[plugins.inputs.audits]]
    url = "https://links.vernaillen.com/"

[[redirects]]
  from = "/plio/js/script.js"
  to = "https://plausible.io/js/script.js"
  status = 200
  force = true

[[redirects]]
  from = "/plio/api/event"
  to = "https://plausible.io/api/event"
  status = 200
  force = true