version: 2.1

orbs:
  slack: circleci/slack@4.12.1

executors:
  pnpm-executor:
    docker:
      - image: vernaillen/circleci-pnpm:19.7.0-browsers

jobs:
  build:
    executor: pnpm-executor
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install packages
          command: pnpm install --frozen-lockfile
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Build
          command: pnpm run build
      - run:
          name: Lint
          command: pnpm run lint
      - run:
          name: Test
          command: pnpm run coverage
      - run:
          name: Install Cypress
          command: pnpm run cy:install
      - run:
          name: Run Cypress
          command: pnpm run cy:run 
      - slack/notify:
          channel: circleci
          event: always

workflows:
  flow:
    jobs:
      - build:
          context: 
            - Slack

# VS Code Extension Version: 1.5.1
